export const SET_EXAMPLE = "SET_EXAMPLE";
export const SET_EXAMPLE_BOOL = "SET_EXAMPLE_BOOL";
export const SET_EXAMPLE_OBJ = "SET_EXAMPLE_OBJ";
export const SET_EXAMPLE_ARR = "SET_EXAMPLE_ARR";
export const TOGGLE_EXAMPLE_BOOL = "TOGGLE_EXAMPLE_BOOL";
